@id=1fe51e58-e116-4986-ad87-3d829552b856

PUT https://localhost:5001/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Ugali na spinach",
    "description": "Kenya Kumethoka. Economy hii si ya mama ya mtu",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savoury": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}