@id=b0e8bc13-f91b-46b6-9aa8-c234b6e163db

PUT https://localhost:5001/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Ugali na spinach",
    "description": "Kenya Kumethoka. Economy hii si ya mama ya mtu",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savoury": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}